### ISSUE TITLE
[GNOME 40] Titlebar Broken

### ISSUE THREAD

**Issue by Arcayr** [TheGreatMcPain/gruvbox-material-gtk#10]
Hey there,

Loving the colour scheme. Installed this on Fedora 34 using GNOME 40, and discovered that the application title bar doesn't want to play ball:
![image](https://user-images.githubusercontent.com/11192354/133069330-96531bb3-9df9-4c65-81d4-69561c5c7e76.png)

I've clean-installed the theme twice, and tried both `/usr/share/themes` and `~/.local/share/themes`, to no avail.

**Comment by TheGreatMcPain** [comment]
Unfortunately since I don't use titlebar's (I don't use a desktop environment) I can't really test to see if this happens on my end.

I can see if regenerating the theme with the latest version of [oomox](https://github.com/themix-project/oomox) will fix it.

Also, I think the image looks completely off which makes me wonder if it's a GNOME issue.  Have you restarted GNOME after applying the theme?

**Comment by Arcayr** [comment]
Hey there, thanks for getting back to me so quickly!

I have, yes. Both logout/login and a full reboot of the system.

**Comment by Arcayr** [comment]
I think I found the issue: I was playing around with other tooling related to creating gresource files to theme GDM (an exercise in more painful futility as the GNOME developers are vehemently opposed to self-expression in any form) and had moved `/usr/share/themes/Default`, which this relies on, to `/usr/share/themes/Adwaita`. Moving it back solved the problem for most applications excluding Discord:

![image](https://user-images.githubusercontent.com/11192354/133563831-ba88c714-af30-45a7-a2d4-574eb7a52917.png)

Thanks!
